"""empty message

Revision ID: 9fb6ce7f9122
Revises: fb6f4f02b4bf
Create Date: 2022-11-06 10:45:46.936079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fb6ce7f9122'
down_revision = 'fb6f4f02b4bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('video_views', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'video_views')
    # ### end Alembic commands ###
